# Should be a directory above the luigi tasks python code

# Configuration for the data files
data:
  raw: '../datasets/titanic.csv'
  clean: '../data/clean_titanic_data.csv'
  train: '../data/training_data.csv'
  test: '../data/test_data.csv'

# Configuration for the model files
model:
  path: '../model/model.yaml'
  weights: '../model/weights.h5'
